### PR TITLE
Toolbar styles

### PR DESCRIPTION
**Pull request by wanderzell**
Here is the first version of the bottom-fixed toolbar with related fixes. Please check if you can merge it. Or if you prefer I can do it myself.

### CODE REVIEW

**Comment by skaman82** [comment]
Thanks a lot for the fix! I really don't know how to merge this. Transferring all your changes by hand is a lot of work. Could you try to merge your fix into current state? Please check how the save buttons look in my version. In your version they are styled differently.

**Comment by wanderzell** [comment]
Okay, I can do merge right away, ok? The button styling is rather random, but it can easily adjusted now in main.css Can you point me screen from where can I get the latest styles for it?

**Comment by skaman82** [comment]
I noticed three things in your version:
1. Padding in the tab should be 15px on each side.
2. There is something wrong in collapsed state (to much distance at the top)
3. I get a scroll bar in the collapsed tabs now. I can scroll them to the side.

bildschirmfoto 2015-11-05 um 19 12 43

**Comment by skaman82** [comment]
I'm done with working on this for today. So no more changes are coming from me until tomorrow. You can marge your changes.

**Comment by wanderzell** [comment]
Okay, will do some debugging. Regarding collapsed tab scroll it seems some conflicting changes in our versions - I saw it as well at some moment though I know that I fixed this some time ago. Will take a look.

**Comment by skaman82** [comment]
sorry gave you the wrong numbers. Padding around the tab content should be:

Open: 20px
Collapsed: 15px

**Comment by wanderzell** [comment]
I have now done the merge. Added also minor fixes here and there, and removed odd style rules as I found them. I think it should be safe to pull now. Btw. I did not do much about the toolbar button styles. You can tweak them as you find suitable - styles are in main.css, find "content_toolbar .btn"

Overall it look good. You've done good job on fixing the looks!

I would like to keep cleaning up the CSS. But critical mass seems to be already there. Seems good enough to make PR to the development branch. To get the thing out to the wild.

**Comment by skaman82** [comment]
Thanks a lot for your support! Only five more Tabs to go :) One thing I have noticed now: The 3D Model does not resize anymore with the window (s. screenshot). Could you please fix this small issue before I pull your files? 
bildschirmfoto 2015-11-06 um 00 54 31

**Comment by wanderzell** [comment]
Okay. I'm sure its gonna be easy fix. Look into it tomorrow. I'd suggest
you pull before you do any additional work.

**Comment by skaman82** [comment]
merged

**Comment by skaman82** [comment]
@wanderzell already fixed the problem :)

**Pull request merged**
