### PR TITLE
Profile selector should now work

### PR DESCRIPTION
**Pull request by NightHawk32**
In case you change the profile its settings will be loaded and the currently active tab will be reloaded. If the profile is changed in the PID Tuning Tab the global profile selector is updated to the new selection.

### CODE REVIEW

**Comment by skaman82** [comment]
wow, thanks man. great work on this! Do you looked at the dataflash bar issue tooß (I thought the issues were at least partly related)

**Comment by skaman82** [comment]
just tested this. Working great. Also answers my question regarding data flash functionality. Could you please look in to that next?

**Comment by skaman82** [comment]
@NightHawk32 I think we can now remove the profile selector in the PID Tab - it is misplaced there anyway. What do you think? I could do this in the next days. Do you have a GPS to work on some GPS stuff? 

Maybe we should chat on things we want to do next? Do you have a skype account ? Just send me your contact via eMail to albert@artdivision.de.

**Comment by NightHawk32** [comment]
Just sent you an email. Yes I will have a look at the dataflash next.
We should remove the selector in the PID tab, I was not sure about your plans, so I left it there for the moment. But with two profile selectors it will be a little confusing ;)

I have never used GPS on my copters, I'm just flying acro, but I just had a look and found a NEO6 in my "stock", so I can put up a little setup for development purposes.

**Comment by skaman82** [comment]
@NightHawk32 just found a bug. When I switch to profile 2 or 3 in the selector, quit the app an restart it. It shows always Profile 1.

**Comment by NightHawk32** [comment]
@skaman82 you are right, I removed the app, reloaded it and had exactly the same problem. Fixed it now. Additionally the profile selector gets updated on every status request, this way it should also update when you change profile via sticks on your radio.

**Pull request merged**
